# Generated by Django 5.0.7 on 2025-10-23 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_registration_number', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eld.driver')),
            ],
            options={
                'unique_together': {('driver', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OFF', 'Off Duty'), ('SB', 'Sleeper Berth'), ('DR', 'Driving'), ('ON', 'On Duty (Not Driving)')], max_length=3)),
                ('timestamp', models.DateTimeField()),
                ('location', models.CharField(help_text='Current location, potentially GPS coordinates', max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='eld.dailylog')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
